var searchData=
[
  ['pages_0',['Déployer sur GitHub Pages',['../index.html#autotoc_md49',1,'']]],
  ['paintevent_1',['paintEvent',['../classGrilleWidget.html#afce97f46f26bce8687e52a4f40c81d5c',1,'GrilleWidget']]],
  ['parallélisation_2',['Mise à jour de la grille avec parallélisation',['../md_CONCEPTION.html#autotoc_md78',1,'']]],
  ['parent_3',['parent',['../classGrilleWidget.html#a6b38496dd5b2fd10ed4d8815127c4658',1,'GrilleWidget']]],
  ['passing_4',['Tests couverts (10/10 passing)',['../index.html#autotoc_md40',1,'']]],
  ['pattern_5',['pattern',['../md_CONCEPTION.html#autotoc_md81',1,'State Pattern'],['../md_CONCEPTION.html#autotoc_md80',1,'Strategy Pattern'],['../md_CONCEPTION.html#autotoc_md82',1,'Template Method Pattern']]],
  ['pattern_20implicite_20via_20événements_20qt_6',['Observer Pattern (implicite via événements Qt)',['../md_CONCEPTION.html#autotoc_md84',1,'']]],
  ['pattern_20model_20view_20controller_7',['MVC Pattern (Model-View-Controller)',['../md_CONCEPTION.html#autotoc_md85',1,'']]],
  ['patterns_20de_20conception_20utilisés_8',['patterns de conception utilisés',['../md_CONCEPTION.html#autotoc_md79',1,'4. Patterns de Conception Utilisés'],['../index.html#autotoc_md31',1,'Patterns de conception utilisés']]],
  ['performance_9',['6. Complexité et Performance',['../md_CONCEPTION.html#autotoc_md92',1,'']]],
  ['performances_10',['Performances',['../index.html#autotoc_md52',1,'']]],
  ['placement_20de_20motif_20interactif_11',['Placement de motif interactif',['../md_CONCEPTION.html#autotoc_md71',1,'']]],
  ['placermotif_12',['placermotif',['../classGrille.html#adfa396acb4a6ed658ce916b5dceaa690',1,'Grille::placerMotif()'],['../classJeuDeLaVie.html#a8bf2b5c24e44c400922032a0f697850b',1,'JeuDeLaVie::placerMotif()']]],
  ['plugins_20qt_20si_20qt_20installé_13',['3. Copier les plugins Qt (si Qt installé)',['../index.html#autotoc_md21',1,'']]],
  ['points_20forts_20à_20présenter_14',['Points forts à présenter',['../index.html#autotoc_md56',1,'']]],
  ['polymorphisme_15',['Polymorphisme',['../md_CONCEPTION.html#autotoc_md88',1,'']]],
  ['poo_16',['Architecture POO',['../index.html#autotoc_md29',1,'']]],
  ['poo_20c_17',['🎮 Jeu de la Vie de Conway - Projet POO C++',['../index.html',1,'']]],
  ['pour_20démo_18',['Démarrage rapide pour démo',['../index.html#autotoc_md57',1,'']]],
  ['pour_20le_20projet_20scolaire_19',['Pour le projet scolaire',['../index.html#autotoc_md55',1,'']]],
  ['prérequis_20',['Prérequis',['../index.html#autotoc_md18',1,'']]],
  ['présenter_21',['Points forts à présenter',['../index.html#autotoc_md56',1,'']]],
  ['premiereiteration_22',['premiereIteration',['../classGrille.html#a1e5703ce2156b1c7d85072156357f5b7',1,'Grille']]],
  ['principale_23',['Architecture Principale',['../md_CONCEPTION.html#autotoc_md66',1,'']]],
  ['principale_20du_20programme_24',['Activité principale du programme',['../md_CONCEPTION.html#autotoc_md77',1,'']]],
  ['principes_20solid_20appliqués_25',['Principes SOLID appliqués',['../index.html#autotoc_md30',1,'']]],
  ['professionnelle_20recommandé_26',['1. Interface Qt (Moderne et professionnelle) - RECOMMANDÉ',['../index.html#autotoc_md10',1,'']]],
  ['programme_27',['Activité principale du programme',['../md_CONCEPTION.html#autotoc_md77',1,'']]],
  ['projet_28',['projet',['../index.html#autotoc_md20',1,'2. Compiler le projet'],['../index.html#autotoc_md42',1,'Structure du projet']]],
  ['projet_20poo_20c_29',['🎮 Jeu de la Vie de Conway - Projet POO C++',['../index.html',1,'']]],
  ['projet_20scolaire_30',['Pour le projet scolaire',['../index.html#autotoc_md55',1,'']]]
];
